name: Platform Tests & Build
on: [push]

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [tip]
        os: [ubuntu-latest]

    steps:

    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set version
      run: make set-version

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.1

    - name: Get go dependencies
      run: go get .

    - name: Tests
      run: go test -tags ci ./...

    - name: Wayland Tests
      run: go test -tags ci,wayland ./...
      if: ${{ runner.os == 'Linux' }}

    - name: Update coverage
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        set -e
        go test -tags ci -covermode=atomic -coverprofile=coverage.out ./...
        coverage=`go tool cover -func coverage.out | grep total | tr -s '\t' | cut -f 3 | grep -o '[^%]*'`
        if (( $(echo "$coverage < 1" | bc) )); then echo "Test coverage lowered"; echo "exit 1"; fi
      if: ${{ runner.os == 'Linux' }}

    - name: Update PR Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
      if: ${{ runner.os == 'Linux' && matrix.go-version == '1.19' }}


    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.VERSION }}.${{ github.run_number }}"
        prerelease: false
        title: "${{ env.VERSION }}.${{ github.run_number }}"
